name = "puddle"
target = "erlang"
version = "0.5.0"

description = "A resource pool manager for gleam"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
links = [{title = "Gleam", href = "https://gleam.run"}]
repository = {type = "github", user = "massivefermion", repo = "puddle"}

[dependencies]
gleam_erlang = "~> 0.23"
gleam_otp = "~> 0.8"
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
simplifile = "~> 0.3"
