description = "A resource pool manager for gleam"
name = "puddle"
version = "0.3.0"

licences = ["Apache-2.0"]
links = [{title = "gleam", href = "https://gleam.run"}]
repository = {type = "github", user = "massivefermion", repo = "puddle"}

[dependencies]
gleam_erlang = "~> 0.22"
gleam_otp = "~> 0.7"
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.11"
