name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.16
        with:
          otp-version: '25'
          gleam-version: '0.32'
          rebar3-version: '3'
      - run: gleam test
      - run: gleam format --check src test
